### ISSUE TITLE
What django version is supported?

### ISSUE THREAD

**Issue by cabello** [teddziuba/django-sslserver#28] opened 2014-12-22 21:10 UTC
Hi,

On `requirements.txt` I see the project is enforcing version `1.4`, does it work on version `1.6` or `1.7` as well?

Thanks,

**Comment by ankitml** [comment] 2015-01-02 18:33
I am having problems after migrating Django to 1.7. The issue is with static files, sometimes they stop loading without any error or warning. Is this happening to anyone else?

**Comment by edmenendez** [comment] 2015-12-08 17:06
Based on the syntax of the runsslserver django command I don't think this is compatible with Django versions before 1.8. It's using the new (not backward compatible) syntax.

**Comment by cabello** [comment] 2015-12-08 17:09
We upgraded our Django version and I am currently using Django 1.8, but still not sure if the latest stable version is supported by this project.

**Comment by battlemidget** [comment] 2015-12-08 17:24
@cabello yea it supports 1.8

**Comment by battlemidget** [comment] 2015-12-08 17:25
Fixed in master

**Closed by battlemidget** 2015-12-08 17:25 UTC

**Comment by cabello** [comment] 2015-12-08 17:28
Thanks :)
